export type StateSealKey = keyof typeof StateSeals

interface StateSeal {
  readonly image: string
  readonly title?: string
}

export const StateSeals: Record<string, StateSeal> = {
  Alabama: { image: 'Alabama' },
  Alaska: { image: 'Alaska' },
  Arizona: { image: 'Arizona' },
  Arkansas: { image: 'Arkansas' },
  California: { image: 'California' },
  Colorado: { image: 'Colorado' },
  Connecticut: { image: 'Connecticut' },
  Delaware: { image: 'Delaware' },
  DistrictOfColumbia: { image: 'District-of-Columbia', title: 'District of Columbia' },
  Florida: { image: 'Florida' },
  Georgia: { image: 'Georgia' },
  Guam: { image: 'Guam', title: 'Territory of Guam' },
  Hawaii: { image: 'Hawaii' },
  Idaho: { image: 'Idaho' },
  Illinois: { image: 'Illinois' },
  Iowa: { image: 'Iowa' },
  Indiana: { image: 'Indiana' },
  Kansas: { image: 'Kansas' },
  Kentucky: { image: 'Kentucky' },
  Louisiana: { image: 'Louisiana' },
  Maine: { image: 'Maine' },
  Maryland: { image: 'Maryland' },
  Massachusetts: { image: 'Massachusetts' },
  Michigan: { image: 'Michigan' },
  Minnesota: { image: 'Minnesota' },
  Mississippi: { image: 'Mississippi' },
  Missouri: { image: 'Missouri' },
  Montana: { image: 'Montana' },
  Nebraska: { image: 'Nebraska' },
  NewYork: { image: 'New-York' },
  NorthCarolina: { image: 'North-Carolina' },
  Nevada: { image: 'Nevada' },
  NewHampshire: { image: 'New-Hampshire' },
  NewJersey: { image: 'New-Jersey', title: 'State of New Jersey' },
  NewMexico: { image: 'New-Mexico' },
  NorthDakota: { image: 'North-Dakota' },
  Ohio: { image: 'Ohio' },
  Oklahoma: { image: 'Oklahoma' },
  Oregon: { image: 'Oregon' },
  Pennsylvania: { image: 'Pennsylvania' },
  PuertoRico: { image: 'Puerto-Rico', title: 'Commonwealth of Puerto Rico' },
  RhodeIsland: { image: 'Rhode-Island' },
  SouthCarolina: { image: 'South-Carolina' },
  SouthDakota: { image: 'South-Dakota' },
  Tennessee: { image: 'Tennessee' },
  Texas: { image: 'Texas' },
  US: { image: 'United-States-Seal', title: 'United States of America' },
  USVirginIslands: { image: 'US-Virgin-Islands', title: 'Virgin Islands of the United States' },
  Utah: { image: 'Utah' },
  Vermont: { image: 'Vermont' },
  Virginia: { image: 'Virginia' },
  Washington: { image: 'Washington' },
  WestVirginia: { image: 'West-Virginia' },
  Wisconsin: { image: 'Wisconsin' },
  Wyoming: { image: 'Wyoming' },
} as const
