export type StateSealKey = keyof typeof StateSeals

interface StateSeal {
  readonly darkModeImage: string
  readonly image: string
  readonly title: string
}

export const StateSeals = {
  Alabama: { image: 'Alabama', title: '', darkModeImage: '' },
  Alaska: { image: 'Alaska', title: '', darkModeImage: '' },
  Arizona: { image: 'Arizona', title: '', darkModeImage: '' },
  Arkansas: { image: 'Arkansas', title: '', darkModeImage: '' },
  California: { image: 'California', title: '', darkModeImage: '' },
  Colorado: { image: 'Colorado', title: '', darkModeImage: '' },
  Connecticut: { image: 'Connecticut', title: '', darkModeImage: '' },
  Delaware: { image: 'Delaware', title: '', darkModeImage: '' },
  DistrictOfColumbia: {
    image: 'District-of-Columbia',
    title: 'District of Columbia',
    darkModeImage: '',
  },
  Florida: { image: 'Florida', title: '', darkModeImage: '' },
  Georgia: { image: 'Georgia', title: '', darkModeImage: '' },
  Guam: { image: 'Guam', title: 'Territory of Guam', darkModeImage: '' },
  Hawaii: { image: 'Hawaii', title: '', darkModeImage: '' },
  Idaho: { image: 'Idaho', title: '', darkModeImage: '' },
  Illinois: { image: 'Illinois', title: '', darkModeImage: '' },
  Iowa: { image: 'Iowa', title: '', darkModeImage: '' },
  Indiana: { image: 'Indiana', title: '', darkModeImage: '' },
  Kansas: { image: 'Kansas', title: '', darkModeImage: '' },
  Kentucky: { image: 'Kentucky', title: '', darkModeImage: '' },
  Louisiana: { image: 'Louisiana', title: '', darkModeImage: '' },
  Maine: { image: 'Maine', title: '', darkModeImage: '' },
  Maryland: { image: 'Maryland', title: '', darkModeImage: '' },
  Massachusetts: { image: 'Massachusetts', title: '', darkModeImage: '' },
  Michigan: { image: 'Michigan', title: '', darkModeImage: '' },
  Minnesota: { image: 'Minnesota', title: '', darkModeImage: '' },
  Mississippi: { image: 'Mississippi', title: '', darkModeImage: '' },
  Missouri: { image: 'Missouri', title: '', darkModeImage: '' },
  Montana: { image: 'Montana', title: '', darkModeImage: '' },
  Nebraska: { image: 'Nebraska', title: '', darkModeImage: '' },
  NewYork: { image: 'New-York', title: '', darkModeImage: '' },
  NorthCarolina: { image: 'North-Carolina', title: '', darkModeImage: '' },
  Nevada: { image: 'Nevada', title: '', darkModeImage: '' },
  NewHampshire: { image: 'New-Hampshire', title: '', darkModeImage: '' },
  NewJersey: {
    image: 'New-Jersey',
    title: 'State of New Jersey',
    darkModeImage: 'New-Jersey-White',
  },
  NewMexico: { image: 'New-Mexico', title: '', darkModeImage: '' },
  NorthDakota: { image: 'North-Dakota', title: '', darkModeImage: '' },
  Ohio: { image: 'Ohio', title: '', darkModeImage: '' },
  Oklahoma: { image: 'Oklahoma', title: '', darkModeImage: '' },
  Oregon: { image: 'Oregon', title: '', darkModeImage: '' },
  Pennsylvania: { image: 'Pennsylvania', title: '', darkModeImage: '' },
  PuertoRico: { image: 'Puerto-Rico', title: 'Commonwealth of Puerto Rico', darkModeImage: '' },
  RhodeIsland: { image: 'Rhode-Island', title: '', darkModeImage: '' },
  SouthCarolina: { image: 'South-Carolina', title: '', darkModeImage: '' },
  SouthDakota: { image: 'South-Dakota', title: '', darkModeImage: '' },
  Tennessee: { image: 'Tennessee', title: '', darkModeImage: '' },
  Texas: { image: 'Texas', title: '', darkModeImage: '' },
  US: { image: 'US-Seal', title: 'United States of America', darkModeImage: '' },
  USVirginIslands: {
    image: 'US-Virgin-Islands',
    title: 'Virgin Islands of the United States',
    darkModeImage: '',
  },
  Utah: { image: 'Utah', title: '', darkModeImage: '' },
  Vermont: { image: 'Vermont', title: '', darkModeImage: '' },
  Virginia: { image: 'Virginia', title: '', darkModeImage: '' },
  Washington: { image: 'Washington', title: '', darkModeImage: '' },
  WestVirginia: { image: 'West-Virginia', title: '', darkModeImage: '' },
  Wisconsin: { image: 'Wisconsin', title: '', darkModeImage: '' },
  Wyoming: { image: 'Wyoming', title: '', darkModeImage: '' },
} as const satisfies Record<string, StateSeal>
